### ISSUE TITLE
TypeError: Cannot read property 'defaultMJMLDefinition' of undefined

### ISSUE THREAD

**Issue by ugogo** [mjmlio/mjml#194]
Hey guys,

Just tried MJML and so far it's really good!

I wanted to create a component, so i did `mjml --init-component foo`, then put `<mj-foo>content</mj-foo>` in my `index.mjml`, but when i compile it, i got an error 
```
TypeError: Cannot read property 'defaultMJMLDefinition' of undefined
    at parseNode (/Users/ugo/Sites/solid-emails/node_modules/mjml/lib/helpers/mjml.js:24:115)
    at Array.map (native)
    at parseNode (/Users/ugo/Sites/solid-emails/node_modules/mjml/lib/helpers/mjml.js:27:39)
    at Array.map (native)
    at parseNode (/Users/ugo/Sites/solid-emails/node_modules/mjml/lib/helpers/mjml.js:27:39)
    at Array.map (native)
    at parseNode (/Users/ugo/Sites/solid-emails/node_modules/mjml/lib/helpers/mjml.js:27:39)
    at parseInstance (/Users/ugo/Sites/solid-emails/node_modules/mjml/lib/helpers/mjml.js:32:33)
    at render (/Users/ugo/Sites/solid-emails/node_modules/mjml/lib/mjml2html.js:221:149)
    at mjml2html (/Users/ugo/Sites/solid-emails/node_modules/mjml/lib/mjml2html.js:65:14)
```

Any idea?
Thanks.

**Comment by GuillaumeBadi** [comment]
Hey !

Can you paste what you've done so far in the component file ?

**Comment by ugogo** [comment]
Hi @GuillaumeBadi, sure!

```
<mj-body background-color="#fff">



  <!-- Logo -->
  <mj-section width="600" align="center" padding="40px 0px 0px 0px">
    <mj-column>
      <mj-image width="65px" src="../images/solid-logo.png"></mj-image>
    </mj-column>
  </mj-section>



  <!-- Divider -->
  <mj-section width="600" padding="20px 0px">
    <mj-column>
      <mj-divider
        width="600"
        padding="0px"
        border-width="1px"
        border-style="solid"
        border-color="#d5d9da"
      ></mj-divider>
    </mj-column>
  </mj-section>

  <!-- Meeting resume -->
  <mj-section width="600" padding="0px">
    <mj-column vertical-align="middle" width="350">
      <mj-text
        padding="5px 0px 5px 0px"
        font-family="Helvetica"
        font-size="16"
        color="#07698D"
        font-weight="bold"
      >Kickoff produit Team Wisembly</mj-text>

      <mj-text
        padding="0px"
        font-family="Helvetica"
        font-size="14"
        color="#708189"
      >December 16th, 2015 • 3:30 PM to 4:30 PM</mj-text>
    </mj-column>

    <mj-column vertical-align="middle" width="130">
      <mj-button
        align="right"
        href="#"
        padding="8px 20px"
        font-family="Helvetica"
        background-color="#46B489"
        href="#"
      >View on Solid</mj-button>
    </mj-column>
  </mj-section>

  <!-- Divider -->
  <mj-section width="600" padding="20px 0px">
    <mj-column>
      <mj-divider
        width="600"
        padding="0px"
        border-width="1px"
        border-style="solid"
        border-color="#d5d9da"
      ></mj-divider>
    </mj-column>
  </mj-section>



  <!-- Note Item -->
  <mj-section width="600" padding="5px 0px">
    <mj-column>
      <mj-text
        padding="5px 0px"
        font-family="Helvetica"
        font-size="14"
        font-weight="bold"
        color="#3A434C"
      >Item</mj-text>
    </mj-column>
  </mj-section>

  <!-- Note Decision -->
  <mj-section width="600" padding="5px 0px">
    <mj-column vertical-align="middle" width="30px">
      <mj-image
        align="left"
        width="18px"
        height="18px"
        padding="0px"
        src="../images/note--decision.png"
      ></mj-image>
    </mj-column>

    <mj-column vertical-align="middle" width="570px">
      <mj-text
        padding="5px 0px"
        font-family="Helvetica"
        font-size="14"
        color="#3A434C"
      >Decision</mj-text>
    </mj-column>
  </mj-section>

  <!-- Note Issue -->
  <mj-section width="600" padding="5px 0px">
    <mj-column vertical-align="middle" width="30px">
      <mj-image
        align="left"
        width="18px"
        height="18px"
        padding="0px"
        src="../images/note--issue.png"
      ></mj-image>
    </mj-column>

    <mj-column vertical-align="middle" width="570px">
      <mj-text
        padding="5px 0px"
        font-family="Helvetica"
        font-size="14"
        color="#3A434C"
      >Issue</mj-text>
    </mj-column>
  </mj-section>


  <!-- Note Task -->
  <mj-section width="600" padding="5px 0px">
    <mj-column vertical-align="middle" width="30px">
      <mj-image
        align="left"
        width="18px"
        height="18px"
        padding="0px"
        src="../images/note--task.png"
      ></mj-image>
    </mj-column>

    <mj-column vertical-align="middle" width="570px">
      <mj-text
        padding="5px 0px"
        font-family="Helvetica"
        font-size="14"
        color="#3A434C"
      >Task</mj-text>
    </mj-column>
  </mj-section>



  <!-- Note component -->
  <mj-section width="600" padding="5px 0px">
    <mj-column vertical-align="middle" width="30px">
      <mj-note>Test</mj-note>
    </mj-column>
  </mj-section>




  <!-- Divider -->
  <mj-section width="600" padding="20px 0px">
    <mj-column>
      <mj-divider
        width="600"
        padding="0px"
        border-width="1px"
        border-style="solid"
        border-color="#d5d9da"
      ></mj-divider>
    </mj-column>
  </mj-section>



  <!-- Footer -->
  <mj-section width="600" padding="10px 0px 0px 0px">
    <mj-column>
      <mj-text
        align="center"
        padding="0px"
        font-family="Helvetica"
        font-size="12"
        color="#708189"
      >This agenda of <a style="color:#708189;" href="#">Kickoff Produit Team Wisembly</a> was sent out by Thibault Davoult with Solid</mj-text>
    </mj-column>
  </mj-section>

  <!-- Divider -->
  <mj-section width="600" padding="20px 0px">
    <mj-column>
      <mj-divider
        width="15"
        padding="0px"
        border-width="3px"
        border-style="solid"
        border-color="#D5D9DA"
      ></mj-divider>
    </mj-column>
  </mj-section>

  <!-- Footer -->
  <mj-section width="600" padding="0px 0px 20px 0px">
    <mj-column>
      <mj-text
        align="center"
        padding="0px"
        font-family="Helvetica"
        font-size="12"
        color="#708189"
      >Solid is made by <a style="color:#07698D;" href="#">Wisembly</a></mj-text>
    </mj-column>
  </mj-section>

</mj-body>
```

As you can see, I've multiple types of `note`, so I tried to create a note component.

**Comment by GuillaumeBadi** [comment]
At the moment, if you want to compile a file, you will have to create a js file, `import mjml` and `import yourComponent` before starting the rendering. Or you might as well use the [MJML starter kit](https://github.com/epayet/mjml-starter-kit) which does this for you.

**Comment by ugogo** [comment]
Mh ok, thx!
