### ISSUE TITLE
Cannot parse mjml string if node process has no permissions on current directory

### ISSUE THREAD

**Issue by sloonz** [mjmlio/mjml#1977]
If the nodejs process has no permission to read the current directory, parsing an MJML string fails. Simple script : 

`require('mjml')('<mjml></mjml')`

Put this in `/home/test-user/test.js`. Switch to root, then do

`cd /root; sudo -u test-user node /home/test-user/test.js`

This fails with : 

```
Error: Specified filePath does not exist
    at MJMLParser (/home/test-user/node_modules/mjml-parser-xml/lib/index.js:85:13)
    at Object.mjml2html [as default] (/home/test-user/node_modules/mjml-core/lib/index.js:193:42)
    at main (/home/test-user/send-alerts.js:173:48)
```

Moreover, mjml will complain being unable to read its configuration file (but this is not a fatal error) : 

```
Error reading mjmlconfig :  Error: EACCES: permission denied, open '/root/.mjmlconfig'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at readMjmlConfig (/home/test-user/node_modules/mjml-core/lib/helpers/mjmlconfig.js:30:48)
    at handleMjmlConfig (/home/test-user/node_modules/mjml-core/lib/helpers/mjmlconfig.js:135:25)
    at Object.<anonymous> (/home/test-user/node_modules/mjml-core/lib/index.js:410:28)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/test-user/node_modules/mjml/lib/index.js:10:41)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/root/.mjmlconfig'
}
```

**Comment by iRyusa** [comment]
Will be a bit hard to fix, maybe if we can just ignore filePath option if mj-include is disabled @kmcb777 ?

**Comment by kmcb777** [comment]
@iRyusa for the filePath i agree that it would be the best solution
concerning .mjmlconfig, i think we should just handle this case as if no mjmlconfig file has been found, it shouldn't be blocking anyway, what do you think ?

**Comment by sloonz** [comment]
Speaking as a user, what weirded me out is mjml trying filesystem accesses when nothing in my code used any file. Had I used includes, I would not have considered as a bug that access to current working directory was required.

If I read the code right (https://github.com/mjmlio/mjml/blob/master/packages/mjml-parser-xml/src/index.js#L44), the error comes from resolving `cwd`, which is only used by `handleInclude`. Why not move the `cwd` resolution inside `handleInclude` ?

**Comment by kmcb777** [comment]
unfortunately cwd is also used in the parsing to determine `absoluteFilePath`, but this one is only used for validation errors messages so we don't need to try to read it
so what we could do is assume that filePath is a dir in the first place because there is no risk doing this, and only in `handleInclude` determine if it's a directory

**Comment by iRyusa** [comment]
> Speaking as a user, what weirded me out is mjml trying filesystem accesses when nothing in my code used any file. Had I used includes, I would not have considered as a bug that access to current working directory was required.

Yep, I think mj-include shouldn't be part of mjml parser but there's no way to fully replace them "on the fly" sadly. Even if it's a convenient feature for users, it should be handled with a templating language (imo, it would support, layout, include & other stuff) but now that's here and a lot of developer are using it, we can't really do something about it.

**Comment by iRyusa** [comment]
I think we did solve this one by wrapping the mjmlconfing in a try catch https://github.com/mjmlio/mjml/blob/43b164b3f5095169ea301b5f68c7e5bdab6d4a5e/packages/mjml-core/src/helpers/mjmlconfig.js#L7 

Please reopen if needed
