### ISSUE TITLE
-w option doesn't compile file

### ISSUE THREAD

**Issue by pixelize** [mjmlio/mjml#219]
Hey guys,

I just updated to 2.0.1, I'm using the -w option with
`mjml -w email/email.mjml -o email/email.html`
 but the .mjml file is not compiled. In fact when I save my file I got an error : 

```
../node_modules/.bin/mjml -w test.mjml -o  test.html
Warning: Please upgrade your MJML markup to add a <mjml> root tag, <mj-body> as root will no longer be supported soon, see https://github.com/mjmlio/mjml/UPGRADE.MD
TypeError: Cannot read property 'length' of undefined
    at documentParser (/Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:97:11)
    at MJMLRenderer.parseDocument (/Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:109:45)
    at new MJMLRenderer (/Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:76:12)
    at /Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-cli/lib/client.js:107:12
Warning: Please upgrade your MJML markup to add a <mjml> root tag, <mj-body> as root will no longer be supported soon, see https://github.com/mjmlio/mjml/UPGRADE.MD
TypeError: Cannot read property 'length' of undefined
    at documentParser (/Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-core/lib/parsers/document.js:97:11)
    at MJMLRenderer.parseDocument (/Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:109:45)
    at new MJMLRenderer (/Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:76:12)
    at /Users/gauthier/Repos/test/node_modules/mjml/node_modules/mjml-cli/lib/client.js:107:12
```

When I'm using without -w
`mjml test.mjml -o test.html`
the file is compiled so I guess it comes from the watch option.

Thanks for help ;)

Here is my markup:

```
<mjml>
  <mj-body>
    <mj-container background-color="#FAFBFB">
      <mj-section padding="60px" full-width="full-width" background-color="#F84F4F">
        <mj-column>

          <mj-text color="#FFF" align="center" font-family="Helvetica, Arial, sans-serif" font-size="24px" font-weight="300" padding="40px 0 15px 0">
            Merci pour votre commande !
          </mj-text>

        </mj-column>
      </mj-section>
    </mj-container>
  </mj-body>
</mjml>
```

**Comment by iRyusa** [comment]
Hello,

Related to #119 , please update your `MJML` to `2.0.2` it has been patched 👍

**Comment by pixelize** [comment]
Hi @iRyusa,

Thanks for the quick reply, sorry didn't see you update 1 hour ago ;)
Keep up the good work, mjml is amazing ! :-)
