### ISSUE TITLE
gulp watch not properly configured?

### ISSUE THREAD

**Issue by paOol** [mjmlio/mjml#232]
```
            throw new _Error.UnknownMJMLElement('Could not find element for :
' + elem.get('tagName'));
              ^

Error: [MJMLError] UnknownMJMLElement: Could not find element for : mj-container

    at MJMLError.Error (native)
    at new MJMLError (( my file directory)) \node_modules\mjml\lib\Error.js:24:85)
    at ( my file directory)) \node_modules\mjml \lib\components\MJMLElement.js:172:21
    at ( my file directory)) \node_modules\immu table\dist\immutable.js:3004:46
    at List.__iterate (( my file directory)) \n ode_modules\immutable\dist\immutable.js:2194:13)
    at IndexedIterable.mappedSequence.__iterateUncached ( \node_modules\immutable\dist\immutable.js:3003:2
3)
    at seqIterate (( my file directory)) \node_ modules\immutable\dist\immutable.js:606:16)
    at IndexedIterable.IndexedSeq.__iterate  \node_modules\immutable\dist\immutable.js:322:14) at IndexedIterable.mixin.toArray  (\node_modules\immutable\dist\immutable.js:4236:23)
    at new List (( my file directory)) \node_mo dules\immutable\dist\immutable.js:2053:62)

```

I get that error when trying to setup gulp watch and saving my code. I have tested with a template so the code should be fine.

If I do mjml --watch instead of using gulp, it works correctly.

Here is the gulp.js

```
var gulp = require('gulp'),
  mjml= require('gulp-mjml');


  gulp.task('mjml', function(){

    return gulp.src('*.mjml')

      .pipe(mjml())
      .pipe(gulp.dest('./html'));

  });


  gulp.task('watch', function(){
    gulp.watch('*.mjml', ['mjml']);
  });


  gulp.task('default', ['watch']);

```

**Comment by GuillaumeBadi** [comment]
Hey, Can you provide your version of gulp-mjml, mjml, and your mjml template ?

**Comment by paOol** [comment]
npm is 3.3.3
gulp is 3.9.1
mjml 2.0.0
gulp-mjml 1.0.0

tried all templates, same issue.

**Comment by GuillaumeBadi** [comment]
Can you try with the latest `gulp-mjml` release ?

**Comment by iRyusa** [comment]
Hi, 
No news on it ? Feel free to re-open if needed
