### ISSUE TITLE
mjml -r input.mjml = TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DylanOpet** [mjmlio/mjml#36]
DylanMBPr-2:/ dylanet$ mjml -r input.mjml
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/mjml/lib/cli.js:71:23
    at /usr/local/lib/node_modules/mjml/lib/cli.js:43:17
    at /usr/local/lib/node_modules/mjml/lib/cli.js:42:12
    at Object.render (/usr/local/lib/node_modules/mjml/lib/cli.js:85:3)
    at main (/usr/local/lib/node_modules/mjml/lib/mjml:35:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/mjml/lib/mjml:52:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
DylanMBPr-2:/ dylanet$

**Comment by iRyusa** [comment]
Hey there @DylanOpet  !
 
Can you provide your node version and your `input.mjml` ?

**Comment by DylanOpet** [comment]
Ah, I don't have an input.mjml I thought thats what might have generated one? :-)

npm WARN engine kind-of@3.0.2: **wanted: {"node":">=0.10.0"} (current: {"node":"0.13.0-pre","npm":"2.11.2"})**

**Comment by iRyusa** [comment]
`mjml -r input.mjml` compiles your `input.mjml` as `output.html`

Closing then if there's no error :)

**Comment by DylanOpet** [comment]
Okay, I now have my input.mjml that I retrieved from the third template and named it that, now tried to render it as output and get the same error, I'm in the same directory of input.mjml/etc.

DylanMBPr-2:mjml dylant$ mjml -r input.mjml
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/mjml/lib/cli.js:71:23
    at /usr/local/lib/node_modules/mjml/lib/cli.js:43:17
    at /usr/local/lib/node_modules/mjml/lib/cli.js:42:12
    at Object.render (/usr/local/lib/node_modules/mjml/lib/cli.js:85:3)
    at main (/usr/local/lib/node_modules/mjml/lib/mjml:35:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/mjml/lib/mjml:52:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by iRyusa** [comment]
Can you try to upgrade your node to the latest version ? At least node 4.3.

https://nodejs.org/en/

It might be an issue with your node version

**Comment by DylanOpet** [comment]
Ahhh, I'm sorry for that! Exactly my issue, truly appreciate the awesome fast support. VERY excited to start playing with this! Kudos!!

**Comment by iRyusa** [comment]
Let me know if you have any problems ! Thanks :+1:
