### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by asha23** [mjmlio/mjml#50]
I am getting this error. Something to do with React.

Warning: React.renderToStaticMarkup is deprecated. Please use ReactDOMServer.renderToStaticMarkup from require('react-dom/server') instead.
Invariant Violation: renderToStaticMarkup(): You must pass a valid ReactElement.
    at invariant (/usr/local/lib/node_modules/mjml/node_modules/fbjs/lib/invariant.js:39:15)
    at Object.renderToStaticMarkup (/usr/local/lib/node_modules/mjml/node_modules/react/lib/ReactServerRendering.js:59:83)
    at Object.newFn [as renderToStaticMarkup] (/usr/local/lib/node_modules/mjml/node_modules/react/lib/deprecated.js:38:17)
    at MJMLElement.mjContent (/usr/local/lib/node_modules/mjml/lib/components/decorators/MJMLElement.js:102:96)
    at Text.render (/usr/local/lib/node_modules/mjml/lib/components/Text.js:85:44)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/usr/local/lib/node_modules/mjml/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (/usr/local/lib/node_modules/mjml/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at wrapper [as _renderValidatedComponent] (/usr/local/lib/node_modules/mjml/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactCompositeComponentMixin.mountComponent (/usr/local/lib/node_modules/mjml/node_modules/react/lib/ReactCompositeComponent.js:220:30)

    at wrapper [as mountComponent] (/usr/local/lib/node_modules/mjml/node_modules/react/lib/ReactPerf.js:66:21)

**Comment by iRyusa** [comment]
Hi @asha23 !

This can happen with an empty tag like `mj-text` it will be fix in `1.1.1` 

Thanks for reporting !

**Comment by asha23** [comment]
Thanks for your reply... I actually re-cloned it all from here and it appears to be working correctly now :)

Nice work, this. By the way... I'll be following it with great interest.

**Comment by arnaudbreton** [comment]
@asha23 thanks for following up. Glad it works now! Please close the issue if nothing more is needed from your side :)
