### ISSUE TITLE
Cannot find module '../lib/index' ERROR when executed

### ISSUE THREAD

**Issue by udezekene** [mjmlio/mjml#507]
Post install when I ran `mjml -w index.mjml -o index.html` I got the error below.
NOTE: index.mjml is still empty.

module.js:471
    throw err;
    ^
Error: Cannot find module '../lib/index'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/udezekene/Dropbox/Sites/usable.newletter/node_modules/.bin/mjml:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by iRyusa** [comment]
Hi 
Can you share your MJML version please @udezekene  ?

**Comment by udezekene** [comment]
@iRyusa It's mjml@3.2.0.

I just noticed I can't even run anything `mjml` command

**Comment by iRyusa** [comment]
Can you try to reinstall it, looks like you're missing transpiled files in your mjml directory

**Comment by udezekene** [comment]
okay. I'll give it another shot @iRyusa. Thanks

**Comment by iRyusa** [comment]
Hey ! Any news on that @udezekene ?

**Comment by udezekene** [comment]
@iRyusa Just re-installed. it's working now. Thank you 👍
