### ISSUE TITLE
Specific class name in mj-raw result in a crash on widthParser

### ISSUE THREAD

**Issue by meriadec** [mjmlio/mjml#608]
related to [mjml-app#84](https://github.com/mjmlio/mjml-app/issues/84)

**mjml:** 3.3.0
**input:**
```
<mjml>
  <mj-body>
    <mj-container>

      <mj-raw>
        <div class="mj-column-per"></div>
      </mj-raw>

      <mj-section>
      </mj-section>

    </mj-container>
  </mj-body>
</mjml>
```
**stacktrace:**
```
TypeError: Cannot read property 'toString' of undefined
    at Object.widthParser (/usr/lib/node_modules/mjml/node_modules/mjml-core/lib/helpers/mjAttribute.js:21:39)
    at /usr/lib/node_modules/mjml/node_modules/mjml-column/lib/index.js:70:52
    at Array.forEach (native)
    at /usr/lib/node_modules/mjml/node_modules/mjml-column/lib/index.js:69:39
    at /usr/lib/node_modules/mjml/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/usr/lib/node_modules/mjml/node_modules/lodash/_baseForOwn.js:13:20)
    at /usr/lib/node_modules/mjml/node_modules/lodash/_createBaseEach.js:17:14
    at forEach (/usr/lib/node_modules/mjml/node_modules/lodash/forEach.js:38:10)
    at postRender (/usr/lib/node_modules/mjml/node_modules/mjml-column/lib/index.js:61:22)
    at /usr/lib/node_modules/mjml/node_modules/mjml-core/lib/MJMLRenderer.js:234:15
```

- if I remove the `mj-section`: it doesn't throw
- if I rename `mj-column-per` by whatever (even `mj-column`): it doesn't throw
- if I don't run mjml at all: it doesn't throw

**Comment by iRyusa** [comment]
Hi @meriadec ;)

Probably need to catch this case in the postRender of `mj-column` cf : https://github.com/mjmlio/mjml/blob/master/packages/mjml-column/src/index.js#L31

**Comment by auzelac91** [comment]
I have the same problem. Mine goes like this:

```
<mj-raw>
  <div style="margin:0px auto;max-width:600px;background:#ffffff;">
    <table role="presentation" style="font-size:0px;width:100%;background:#ffffff;" cellspacing="0" cellpadding="0" border="0" align="center">
      <tbody>
         <tr>
           <td style="text-align:center;vertical-align:top;direction:ltr;font-size:0px;padding:0px 0px;padding-bottom:20px;">
             <div class="mj-column-per-100 outlook-group-fix" style="vertical-align:top;display:inline-block;direction:ltr;font-size:13px;text-align:left;width:100%;">
             </div>
           </td>
         </tr>
       </tbody>
     </table>
   </div>
</mj-raw>
```

I get this:
```
TypeError: Cannot read property 'toString' of undefined
    at Object.widthParser (C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-core\lib\helpers\mjAttribute.js:21:39)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-column\lib\index.js:70:52
    at Array.forEach (native)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-column\lib\index.js:69:39
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\lodash\_createBaseFor.js:17:11
    at baseForOwn (C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\lodash\_baseForOwn.js:13:20)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\lodash\_createBaseEach.js:17:14
    at forEach (C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\lodash\forEach.js:38:10)
    at postRender (C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-column\lib\index.js:61:22)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\mjml\node_modules\mjml-core\lib\MJMLRenderer.js:260:15
```

When I remove `mj-column-per-100`, it works.
Tested in the latest version and in beta.

Will it be a fix for this?

**Comment by iRyusa** [comment]
Sorry for responding late, You can add a `data-column-width` to the div with a value of `100%` if you're in a `mj-column-per-100` or `600px` if you're in a `mj-colum-px-600`.

I'm closing this, because those class should be used for internal stuff only, so if you want to avoid the crash just add the `data-column-width`

**Comment by Uelb** [comment]
I'm not sure it's a relevant case but here is my use case : 
- I send an email using an mjml template to my customer
- He answers me, so I get the original email back inside the answer, with those classes (Re:)
- I take his answer, and try to answer him back again (using my platform, so using mjml), but if I insert his first answer, then the mjml parser crashes cause it with the error mentioned in this issue (Re: Re:)
