### ISSUE TITLE
Error with generated custom component when rendering MJMLElements

### ISSUE THREAD

**Issue by epayet** [mjmlio/mjml#62]
I am using the template generated by `mjml --init-component product`. When I try to render a MJMLElement (default generated render method), I have an error. Here is the render method:

```javascript
render() {

    const css = this.getStyles(),
          content = 'Hello World!'

    return (
      <MjText style={ css }>
        { content }
      </MjText>
    )
  }
```

The error is when running the command `DEBUG="mjml-engine/mjml2html" babel-node app.js`

```
  mjml-engine/mjml2html Start parsing content +0ms
  mjml-engine/mjml2html Content parsed. +8ms
  mjml-engine/mjml2html Start rendering +1ms
  mjml-engine/mjml2html Create root React element +0ms
  mjml-engine/mjml2html Render to static markup +0ms
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <td>. See MJMLColumnElement > td > Product > MJMLElement > MJMLColumnElement > tr.
Warning: React.renderToStaticMarkup is deprecated. Please use ReactDOMServer.renderToStaticMarkup from require('react-dom/server') instead.
/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/fbjs/lib/invariant.js:46
    throw error;
    ^

Invariant Violation: renderToStaticMarkup(): You must pass a valid ReactElement.
    at invariant (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/fbjs/lib/invariant.js:39:15)
    at Object.renderToStaticMarkup (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/react/lib/ReactServerRendering.js:59:83)
    at Object.newFn [as renderToStaticMarkup] (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/react/lib/deprecated.js:38:17)
    at MJMLElement.mjContent (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/mjml/lib/components/decorators/MJMLElement.js:102:96)
    at Text.render (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/mjml/lib/components/Text.js:85:44)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].wrapper [as _renderValidatedComponent] (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/react/lib/ReactPerf.js:66:21)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at [object Object].wrapper [as mountComponent] (/Users/c2249657/WebstormProjects/responsive-email-desssipi/node_modules/react/lib/ReactPerf.js:66:21)
```

Here is my app.js: 

```javascript
import Product from './Product'
import mjml from 'mjml'

/*
  Compile an mjml string
*/
const htmlOutput = mjml.mjml2html(`<mj-body>
  <mj-section>
    <mj-column>
      <mj-product></mj-product>
    </mj-column>
  </mj-section>
</mj-body>
`)

/*
  Print the responsive HTML generated
*/
console.log(htmlOutput);
```

However, when I render simple html like this:

```javascript
render() {
    return (
      <span>test</span>
    )
  }
```

It is working fine. I cannot see why I cannot render MJMLElements like MjText but I can render simple html :/

Thanks

**Comment by arnaudbreton** [comment]
Hi @epayet, thanks for reporting. We'll look into it and come back to you with a solution.

Thanks for your patience!

**Comment by iRyusa** [comment]
Hi @epayet , 

If `mj-product` is empty,  `content` is empty so the engine crash. I'll try to fix it today

**Comment by epayet** [comment]
Hi,

Sorry to reopen this issue but the bug isn't resolved even with the version 1.2.0
I made a small repo with the reproduction of this bug: https://github.com/epayet/mjml-bug-component

I cannot see why it is still happening. Could you look into it?
I am happy to help. Thanks

**Comment by iRyusa** [comment]
Ok, I figured out what happen: When giving a non-react element to a `mjText` that depends on `mjContent` it will crash. 

Thank you very much for taking the time to do a repository to reproduce the bug ! I'll try to get a fix for a next release !

**Comment by rogierslag** [comment]
Cool that would be awesome, I ran into exactly the same issu. A slight adjustment to the mjContent method solved it

```jsx
    mjContent() {
      const content = this.state.getIn(['elem', 'content']);
      if ( content ) {
        return _.trim(content)
      }
      return React.Children.map(this.props.children, child => {
        if (typeof child === 'string') {
          return child;
        }
        return ReactDOMServer.renderToStaticMarkup(child)
      })
    }
```

**Comment by iRyusa** [comment]
:+1: @rogierslag if you can open a PR would be so cool ! :)
