### ISSUE TITLE
helpers.startConditionalTag can not appear inside Section or Container

### ISSUE THREAD

**Issue by PickRelated** [mjmlio/mjml#627]
Hi!

Please consider the following code inside my custom component `render` function.
```html
<Container padding="0" key="icons">
  <Section { ...this.props } key="icons-desktop-mso">
    { helpers.startConditionalTag }
      { columnsDesktop }
    { helpers.endConditionalTag }
  </Section>
</Container>
```

It gives me this output.
```bash
{ TypeError: Cannot read property 'mjml' of undefined
    at node_modules/mjml-core/lib/decorators/MJMLElement.js:137:26
    at Array.filter (native)
    at MJMLElement._this.renderWrappedOutlookChildren (node_modules/mjml-core/lib/decorators/MJMLElement.js:136:37)
    at Container.render (node_modules/mjml-container/lib/index.js:111:9)
    at node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
    at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
  name: 'TypeError',
  message: 'Cannot read property \'mjml\' of undefined',
  stack: 'TypeError: Cannot read property \'mjml\' of undefined\n    at node_modules/mjml-core/lib/decorators/MJMLElement.js:137:26\n    at Array.filter (native)\n    at MJMLElement._this.renderWrappedOutlookChildren (node_modules/mjml-core/lib/decorators/MJMLElement.js:136:37)\n    at Container.render (node_modules/mjml-container/lib/index.js:111:9)\n    at node_modules/react-dom/lib/ReactCompositeComponent.js:796:21\n    at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)\n    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)\n    at ReactCompositeComponentWrapper._renderValidatedComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)\n    at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)\n    at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)',
  showStack: false,
  showProperties: true,
  plugin: 'MJML' }
```

However, if I wrap conditional tags into `Text` - it compiles without errors, but brakes the layout in Outlook 2010 and 2013, making columns stack.

```html
<Container padding="0" key="icons">
  <Section { ...this.props } key="icons-desktop-mso">
    <Text>
      { helpers.startConditionalTag }
        { columnsDesktop }
      { helpers.endConditionalTag }
    </Text>
  </Section>
</Container>
```

Any idea how I can use conditional tags to show or hide the entire `Container` or `Section`?
Thanks!

**Comment by iRyusa** [comment]
Hey ! 

You have to put those comments in a Post Render. React doesn't like mso conditionnals

**Comment by iRyusa** [comment]
@PickRelated and you can take look at `mj-section` to see how we're using it: https://github.com/mjmlio/mjml/blob/master/packages/mjml-section/src/index.js

**Comment by iRyusa** [comment]
Well this is a React limitation indeed, you can adds custom div as we do and then just replace them in a `postRender`. It's way more safe than `Text` workaround. 

Yeah this is the purpose of #532 and we're working to merging this ASAP! I'm closing this one because we have no other workaround than adding a placeholder `div`.

**Comment by PickRelated** [comment]
I just can't stop being surprised by the speed you help mjml users. Thank you for all your suggestions and for merging that PR! I will probably refactor my code to use new functionality at a later point.
