### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by ryanjohnsonnc** [mjmlio/mjml#76]
I am continually getting this error while I am trying to invoke mjml on a document

**Comment by GuillaumeBadi** [comment]
Hey @ryanjohnsonnc ! 

What version of node are you using ?

**Comment by ryanjohnsonnc** [comment]
v0.10.31

**Comment by GuillaumeBadi** [comment]
Yep Promises are not compatible with your version of node, I encourage you to update it to the [latest stable release](https://nodejs.org/en/) (or above)

**Comment by ryanjohnsonnc** [comment]
I've done that. Still the same error.

**Comment by GuillaumeBadi** [comment]
I can't reproduce your error, can you show me your code and the output of `node -v` so I can try it on my side ?

**Comment by formermember** [comment]
I had the same issue, I had to uninstall nodejs and npm completely and reinstall the latest version using the installer from the node website.

**Comment by ryanjohnsonnc** [comment]
I did what @formermember said. It seemed to get me a little further along in the process. 

Now the error I get when attempting to run mjml -r index.mml is:

TypeError: Cannot read property 'map' of undefined
    at Social.renderHorizontal (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/lib/components/Social.js:192:53)
    at Social.render (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/lib/components/Social.js:234:36)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at wrapper [as _renderValidatedComponent] (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactPerf.js:66:21)
    at ReactCompositeComponentMixin.mountComponent (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactCompositeComponent.js:220:30)
    at wrapper [as mountComponent] (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/usr/local/Cellar/nvm/0.15.0/v4.3.1/lib/node_modules/mjml/node_modules/react/lib/ReactDOMComponent.js:591:32)


Any ideas?

**Comment by iRyusa** [comment]
Yes It's because of the `1.2`, `mj-social` use a new syntax `<mj-social display="twitter facebook" />` and you'll be fine

**Comment by iRyusa** [comment]
@ryanjohnsonnc can you try it with `1.2.1` ? Thanks !
