### ISSUE TITLE
Error - mjAttribute is not a function

### ISSUE THREAD

**Issue by krike** [mjmlio/mjml#806]
I'm using grunt and I think I have everyting setup correctly. however when the example component is converted using babel and the template converted I get the error 

```
>> error processing file templates/input.mjml
Fatal error: mjAttribute is not a function
```

This is my Gruntfile.js

```
module.exports = function(grunt) {
    grunt.initConfig({
        dirs: {
            templates: 'templates',
            outputTemplates: 'templates-output',
            modules: 'node_modules'
        },

        mjml: {
            options: {},
            your_target: {
                files: [{
                    expand: true,
                    cwd: '<%=dirs.templates%>',
                    src: ['**/*'],
                    dest: '<%=dirs.outputTemplates%>/',
                    ext: '.html.twig',
                    extDot: 'first'
                }]
            }
        },
        babel: {
            options: {
                sourceMap: true,
                presets: ['env']
            },
            dist: {
                files : [{
                    expand: true,
                    src: ['./components/*.js'],
                    dest: 'lib',
                    ext: ".js",
                    flatten: true
                }]
            }
        },
        watch: {
            mjml: {
                files: ['<%=dirs.templates%>/**/*.mjml'],
                tasks: 'mjml'
            },
            babel: {
                files: ['components/*.js'],
                tasks: 'babel'
            }
        }

    });

    // Loading extra tasks
    grunt.loadNpmTasks('grunt-mjml');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-babel');

    // Default call
    grunt.registerTask('default', 'mjml');
};
```

my package.json

```
{
  "name": "mjml-project",
  "version": "1.0.0",
  "description": "MJML test project",
  "devDependencies": {
    "babel-core": "^6.13.2",
    "babel-eslint": "^6.1.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.14.0",
    "eslint": "^3.4.0",
    "eslint-config-airbnb": "^10.0.0",
    "eslint-plugin-import": "^1.13.0",
    "eslint-plugin-jsx-a11y": "^2.1.0",
    "eslint-plugin-react": "^6.0.0",
    "grunt-babel": "^7.0.0"
  },
  "dependencies": {
    "lodash": "^4.15.0",
    "grunt": "^1.0.1",
    "grunt-contrib-watch": "^1.0.0",
    "grunt-mjml": "^1.0.1",
    "mjml": "^3.3.3",
    "mjml-column": "^3.1.1",
    "mjml-core": "^3.1.1",
    "mjml-image": "^3.1.1",
    "mjml-section": "^3.1.1",
    "mjml-text": "^3.1.1",
    "react": "^15.3.1"
  },
  "scripts": {
    "test": "npm test",
    "build-templates": "node build-templates.js"
  },
  "author": "Christophe",
  "license": "ISC"
}
```

**Comment by iRyusa** [comment]
Hi, 

Can you just share the component you're compiling in order to reproduce ? thanks

**Comment by krike** [comment]
here is the mj-column-image-text:
https://pastebin.com/xqz3c4Mp

and this is what it compiles it to:
https://pastebin.com/mQxUq2st

**Comment by iRyusa** [comment]
Both seems fine. Did you try without grunt and directly with mjml cli ?

**Comment by krike** [comment]
Yes I did. same problem but with a bit more information

```
TypeError: mjAttribute is not a function
    at ColumnImageText.renderImage (/Users/krikke/Sites/mjml/lib/MjColumnImageText.js:80:32)
    at ColumnImageText.render (/Users/krikke/Sites/mjml/lib/MjColumnImageText.js:109:27)
    at /Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactCompositeComponent.js:795:21
    at measureLifeCyclePerf (/Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactCompositeComponent.js:794:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactCompositeComponent.js:821:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactCompositeComponent.js:361:30)
    at ReactCompositeComponentWrapper.mountComponent (/Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactCompositeComponent.js:257:21)
    at Object.mountComponent (/Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactReconciler.js:45:35)
    at ReactDOMComponent.mountChildren (/Users/krikke/Sites/mjml/node_modules/react-dom/lib/ReactMultiChild.js:236:44)
```

**Comment by iRyusa** [comment]
Well, I'm unable to reproduce with https://github.com/mjmlio/mjml-component-boilerplate do you ?

What's your node version ?

**Comment by krike** [comment]
unable to reproduce as well with the boilerplate, so there it seems to work perfectly. I compared both compiled js files and it is exactly the same, so I have no idea why mjml in my project fails building it. i'll continue debugging

**Comment by krike** [comment]
I was mistaken there is a difference, i copy pasted the generated component file to my project and it can create the html file.

The difference is the following, in my project:
`var ColumnImageText = function (_Component) {`

in the boilerplate:
`var ColumnImageText = (0, _mjmlCore.MJMLElement)(_class = function (_Component) {`

**Comment by iRyusa** [comment]
You're missing the decorator, did you set a babelrc on your project ?

**Comment by krike** [comment]
I have the `"babel-plugin-transform-decorators-legacy": "^1.3.4",` and it is present in the `.babelrc`:

```
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": ["transform-decorators-legacy"]
}
```
if this is enough to get the decorator to work (normally)?

**Comment by krike** [comment]
it's not a secret project, so if it helps I can provide a copy and if you are willing you can have a look at it?

**Comment by iRyusa** [comment]
Well you can push it to github so I can't take a look but it should be an issue with your build task

**Comment by krike** [comment]
... alright... gulp it is :D :P

**Comment by iRyusa** [comment]
👌
